# Generated by Django 5.0.2 on 2024-02-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='minimum_price',
            new_name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_highest_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
